port: 7005

mysql:
  driver: mysql
  url:
  # connection max life time: default 3 minutes
  max-life-time: 3
  # max open connections: default 10
  max-open-connections: 10
  # max idle connections: default 10
  max-idle-connections: 10

zip:
  # 是否打开vat-note 功能
  vat-note-open: true
  vat-note-dir:
  vat-note-download-uri: http://localhost:7006/generatePdf/vatNote/CUSTOMS_ID

icp:
  save-dir: tmp/

audit:
  tmp-dir: tmp/audit
  save-dir: tmp/audit

oss:
  endpoint:
  access-key:
  access-secret:
  bucket: