/*
Copyright © 2022 Joker

*/
package cmd

import (
	"fmt"
	"github.com/go-playground/validator"
	_ "github.com/go-sql-driver/mysql"
	"github.com/jmoiron/sqlx"
	"github.com/labstack/echo/v4"
	"github.com/spf13/cobra"
	"github.com/spf13/viper"
	echoSwagger "github.com/swaggo/echo-swagger"
	"os"
	_ "sysafari.com/customs/tguard/docs" // docs is generated by Swag CLI, you have to import it.
	"sysafari.com/customs/tguard/global"
	"sysafari.com/customs/tguard/web"
	"time"
)

var cfgFile string

// rootCmd represents the base command when called without any subcommands
var rootCmd = &cobra.Command{
	Use:   "tguard",
	Short: "A brief description of your application",
	Long: `A longer description that spans multiple lines and likely contains
examples and usage of using your application. For example:

Cobra is a CLI library for Go that empowers applications.
This application is a tool to generate the needed files
to quickly create a Cobra application.`,
	// Uncomment the following line if your bare application
	// has an action associated with it:
	Run: func(cmd *cobra.Command, args []string) {
		// Init database connection
		initGlobalDatabaseConnection()

		// At last
		echoRoutes()
	},
}

// Execute adds all child commands to the root command and sets flags appropriately.
// This is called by main.main(). It only needs to happen once to the rootCmd.
func Execute() {
	err := rootCmd.Execute()
	if err != nil {
		os.Exit(1)
	}
}

// echoRoutes Set echo routes
// @title LWT web service
// @version 1.0
// @description This is a simple web service that provides ICP service
// @termsOfService http://swagger.io/terms/

// @contact.name Joker
// @contact.email ljr@y-clouds.com

// @license.name Apache 2.0
// @license.url http://www.apache.org/licenses/LICENSE-2.0.html

// @host localhost:7005
// @BasePath /v2
func echoRoutes() {
	e := echo.New()
	e.Validator = &web.CustomValidator{Validator: validator.New()}
	// swagger
	e.GET("/swagger/*", echoSwagger.WrapHandler)

	e.POST("/icp/append", web.AppendToICP)

	// http://domain.example.com/icp/taxAgency/BE0796544895?month=2022-09
	e.GET("/icp/taxAgency/:dutyParty", web.MakeICPForTaxAgency)

	// download icp file
	// http://domain.example.com/icp/download/BE0796544895_202209_01154020.xlsx
	e.GET("/icp/download/:filename", web.DownloadFile)

	port := viper.GetString("port")
	if port == "" {
		port = "1324"
	}

	fmt.Printf("Tguard server started: %v", e.Start(":"+port))
}

// initGlobalDatabaseConnection sets the global database connection
func initGlobalDatabaseConnection() {
	fmt.Println("init sql connection ....")
	db, err := sqlx.Open("mysql", viper.GetString("mysql.url"))

	if err != nil {
		panic(err)
	}
	// See "Important settings" section.
	db.SetConnMaxLifetime(time.Minute * 3)
	db.SetMaxOpenConns(10)
	db.SetMaxIdleConns(10)
	fmt.Println("db stats:", db.Stats())

	global.Db = db
}

func init() {
	cobra.OnInitialize(initConfig)

	// Here you will define your flags and configuration settings.
	// Cobra supports persistent flags, which, if defined here,
	// will be global for your application.

	rootCmd.PersistentFlags().StringVar(&cfgFile, "config", ".tguard.yaml", "config file (default is $HOME/.tguard.yaml)")

	// Cobra also supports local flags, which will only run
	// when this action is called directly.
	rootCmd.Flags().BoolP("toggle", "t", false, "Help message for toggle")
}

// initConfig reads in config file and ENV variables if set.
func initConfig() {
	if cfgFile != "" {
		// Use config file from the flag.
		viper.SetConfigFile(cfgFile)
	} else {
		// Find home directory.
		home, err := os.UserHomeDir()
		cobra.CheckErr(err)

		// Search config in home directory with name ".tguard" (without extension).
		viper.AddConfigPath(home)
		viper.SetConfigType("yaml")
		viper.SetConfigName(".tguard")
	}

	viper.AutomaticEnv() // read in environment variables that match

	// If a config file is found, read it in.
	if err := viper.ReadInConfig(); err == nil {
		fmt.Fprintln(os.Stderr, "Using config file:", viper.ConfigFileUsed())
	}
}
